# Generated by Django 4.2 on 2025-05-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='products.product')),
            ],
        ),
    ]
