# Generated by Django 4.2 on 2025-05-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_search_vector_product_search_vector_gin_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
