# Generated by Django 4.2 on 2025-05-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name_ar_gin_idx_product_name_en_gin_idx'),
    ]
    operations = [
        migrations.RunSQL(
            # Create immutable wrapper function
            sql="""
            CREATE OR REPLACE FUNCTION unaccent_immutable(text)
            RETURNS text
            LANGUAGE SQL
            IMMUTABLE
            AS $$
                SELECT unaccent($1);
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS unaccent_immutable(text);"
        ),
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS product_name_ar_unaccent_trgm_idx ON products_product USING gin (unaccent_immutable(name_ar) gin_trgm_ops);",
                "CREATE INDEX IF NOT EXISTS product_name_en_unaccent_trgm_idx ON products_product USING gin (unaccent_immutable(name_en) gin_trgm_ops);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS product_name_ar_unaccent_trgm_idx;",
                "DROP INDEX IF EXISTS product_name_en_unaccent_trgm_idx;",
            ],
        ),
    ]
